version: '3.5'
services:
  server:
    build: ./server
    ports:
      - "5566:8080"
    volumes:
      - ServerVolume:/opt/data
      - /var/run/docker.sock:/var/run/docker.sock
  client:
    build: ./client
    ports:
      - "4200:80"
  sonar:
    build: ./sonar
    ports:
      - "9000:9000"
    volumes:
      - SonarVolume:/opt/sonarqube/data
volumes:
  ServerVolume: {}
  SonarVolume: {}
